openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/novis2/IskorkaCinema/1.0.0
info:
  version: "1.0.0"
  title: Iskorka Cinema API + bonuses
  description: API кинотеатра "Искорка"с бонусной программной
paths:
  /timetable/{date}:
    get:
      summary: Получение расписание фильмов на дату
      tags:
        - Расписание
      parameters: 
        - name: date
          in: path
          required: true
          description: Дата расписания сеансов
          schema:
            type: string
            format: date
            example: '2022-07-01'
        - name: page
          in: query
          required: false
          description: Номер страницы
          schema:
            type: integer
            default: 1
            example: 1
        - name: pageSize
          in: query
          required: false
          description: Количество фильмов на странице
          schema:
            type: integer
            default: 10
            example: 10        
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                properties:
                  errors:
                    type: array
                    items: 
                      type: string
                    example: []
                  result:
                    properties:
                      currentPage:
                        description: Текущая страница
                        type: integer
                        example: 1
                      moviesCount: 
                        description: Количество фильмов на странице
                        type: integer
                        example: 10
                      totalPages:
                        description: Число страниц
                        type: integer
                        example: 5
                      movies:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              description: Идентификатор фильма
                              example: 565656
                            title:
                              description: Название фильма
                              type: string
                              example: "Подводная братва"
                            duration:
                              description: Длительность фильма
                              type: string
                              example: "1ч 50мин"
                            screenings:
                              description: Список сеансов
                              type: array
                              items:
                                $ref: '#/components/schemas/TimeString'
                              example:
                                - "10:30"
                                - "13:45"
            application/xml:
              schema:
                type: object
                xml:
                  name: result
                properties:
                  errors:
                    type: array
                    items: 
                      type: string
                    example: []
                  result:
                    properties:
                      currentPage:
                        description: Текущая страница
                        type: integer
                        example: 1
                      moviesCount: 
                        description: Количество фильмов на странице
                        type: integer
                        example: 10
                      totalPages:
                        description: Число страниц
                        type: integer
                        example: 5
                      movies:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              description: Идентификатор фильма
                              example: 565656
                            title:
                              description: Название фильма
                              type: string
                              example: "Подводная братва"
                            duration:
                              description: Длительность фильма
                              type: string
                              example: "1ч 50мин"
                            screenings:
                              description: Список сеансов
                              type: array
                              items:
                                $ref: '#/components/schemas/TimeString'
                              example:
                                - "10:30"
                                - "13:45"
  /places/{screeningId}/all:
    get:
      summary: Получение количества свободных мест на сеансе
      tags:
      - Отображение мест
      parameters:
        - name: screeningId
          in: path
          required: true
          description: Идентификатор сеанса
          schema: 
            type: integer
            example: 12345
      responses:
        200: 
          description: Успешный ответ
          content:
            application/json:
              schema:
                properties: 
                  errors:
                    type: array
                    items: 
                      type: string
                    example: []
                  result:
                    properties:
                      id: 
                        description: Идентификатор сеанса
                        type: integer
                        example: 12345
                      title: 
                        description: Количество свободных мест
                        type: integer
                        example: 10
  /places/{screeningId}:
    get:
      summary: Получение списка мест с указанием доступных
      tags:
      - Отображение мест
      parameters:
          - name: screeningId
            in: path
            required: true
            description: Идентификатор сеанса
            schema: 
              type: integer
              example: 12345
      responses:
        200:
          description: Успешный ответ
          content:
            application/json:
              schema:
                properties:
                  errors:
                      type: array
                      items: 
                        type: string
                      example: []
                  result:
                    properties:
                      id: 
                        description: Идентификатор сеанса
                        type: integer
                        example: 12345
                      title: 
                        description: Количество свободных мест
                        type: integer
                        example: 10
                      placeList:
                        type: array
                        properties:
                          number:
                            description: Номер места
                            type: integer
                          status:
                            description: Статус места
                            type: string
                            enum: 
                              - avialable
                              - booked
                              - occupied
                        example: 
                          - number: 1
                            status: avialable
                          - number: 2
                            status: occupied
  /book/{screeningId}:
    patch:
      summary: Бронирование мест
      description: Запрос для бронирования мест
      tags:
        - Бронирование
      parameters:
        - name: screeningId
          in: path
          required: true
          description: Идентификатор сеанса
          schema: 
            type: integer
            example: 12345
      requestBody:
        content:
          application/json:
            schema:
              properties:
                places:
                  $ref: '#/components/schemas/BasicPlacesList'
                  minItems: 1
      responses:
        200:
          description: Успешное бронирование
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Booking successful
                  booked_places:
                    $ref: '#/components/schemas/BasicPlacesList'
        409:
          description: Места недоступны
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Selected places unavailable
                  unavailable_places:
                    $ref: '#/components/schemas/BasicPlacesList'
  /booking:
    post:
      summary: Оформление заказа
      description: Запрос для бронирования мест
      tags:
        - Бронирование
      requestBody:
        content:
          application/json:
            schema:
              required: [screeningId, places, amount, realAmount] 
              properties:
                screeningId:
                  type: integer
                  example: 12345
                places:
                  $ref: '#/components/schemas/BasicPlacesList'
                  minItems: 1
                amount:
                  $ref: '#/components/schemas/Money'
                bonusCard:
                  type: integer
                  example: 262626
                bonusUsed:
                  type: integer
                realAmount:
                  $ref: '#/components/schemas/Money'
                contactName:
                  type: string
                contactPhoneNumber:
                  type: string
                contactEmail:
                  type: string
      responses:
          200:
            description: Успешное бронирование
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    message:
                      type: string
                      example: Tickets issuing successful
                    screeningId:
                      type: integer
                      example: 12345
                    places:
                      $ref: '#/components/schemas/BasicPlacesList'
                      minItems: 1
                    amount:
                      $ref: '#/components/schemas/Money'
                    bonusCard:
                      type: integer
                      example: 262626
                    bonusUsed:
                      type: integer
                    bonusGet:
                      type: integer
                    totalBonuses:
                      type: integer
                    realAmount:
                      $ref: '#/components/schemas/Money'
                    contactName:
                      type: string
                    contactPhoneNumber:
                      type: string
                    contactEmail:
                      type: string
  /booking/{bookingId}:
    delete:
      summary: Отмена бронирования
      tags:
      - Управление бронированием
      parameters:
          - name: bookingId
            in: path
            required: true
            description: Идентификатор бронирования
            schema: 
              type: integer
              example: 88776655
      responses:
        200:
          description: Успешная отмена бронирования
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Booking cancellation successful
                  booked_places:
                    $ref: '#/components/schemas/BasicPlacesList'
                  screeningId:
                    type: integer
                    example: 12345
  /screening/{screeningId}:
    patch:
      summary: Изменение времени сеанса
      tags: 
      - Функции администратора
      parameters:
          - name: screeningId
            in: path
            required: true
            description: Идентификатор сеанса
            schema: 
              type: integer
              example: 12345
      requestBody:
        content:
          application/json:
            schema:
              properties:
                newTime:
                  type: string
                  format: time
      responses:
        200:
          description: Время сеанса успешно изменено
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Screening time change successful
                  screeningId:
                    type: integer
                    example: 12345
                  screeningDate:
                    type: string
                    format: date
                  screeningTime:
                    type: string
                    format: time
                  movieName:
                    type: string
                    example: Подводная братва
                  auditorium:
                    description: Номер зала
                    type: integer
                    example: 1
        403:
          description: Недостаточно прав на изменение сеанса
          content:
            application/json:
              schema:
                properties: 
                  errors:
                    type: array
                    items: 
                      type: string
                    example: 
                      - У вас недостаточно прав для изменения сеанса
                  result:
                    type: string
                    example: {}      
  /report/bonuses:
    get:
      summary: Запрос отчёта об использовании бонусов за месяц
      tags:
        - Функции администратора
      parameters: 
        - name: year
          in: query
          required: true
          description: Год запроса отчёта
          schema:
            type: integer
            default: 2022
            example: 1
        - name: month
          in: query
          required: true
          description: Номер месяца запроса отчёта
          schema:
            type: integer
            default: 1
            example: 1        
      responses:
        200:
          description: Успешный ответ, возвращает файл с отчётом
          content:
            application/pdf:
              schema:
                type: string
                format: binary
components:
  schemas:
    BasicPlacesList:
      description: Массив со списком мест в зале
      type: array
      items:
        type: integer
      example: [10,11]
    Money:
      description: Стоимость в рублях
      type: string
      pattern: ^[1-9]\d{0,3}\.\d0
    TimeString:
      type: string
      description: Время в формате чч:мм
      pattern: ^([01]\d|2[0-3]):[0-5]\d$
      example: "10:30"
  responses:
    400BadRequest:
      description: Неверный запрос
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Invalid request
    404NotFound:
      description: Ресурс не найден
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Resource not found
    500ServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Internal server error